apiVersion: v1
kind: Service
metadata:
  name: course-app-service
spec:
  type: NodePort
  selector:
    app: course-app
  ports:
    - port: 8080        # порт всередині кластера
      targetPort: 8080  # порт контейнера
      nodePort: 30080   # порт на всіх нодах для зовнішнього доступу
