version: "3.9"

services:
  redis:
    image: redis:7
    volumes:
      - redisdata:/data
    deploy:
      restart_policy:
        condition: any

  course-app:
    image: course-app:latest
    # Прямой проброс порта на хост
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      - REDIS_HOST=redis:6379
    volumes:
      - appdata:/app/data
    deploy:
      restart_policy:
        condition: any

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s


volumes:
  appdata:
  redisdata:
