apiVersion: v1
kind: Service
metadata:
  name: course-app-sv
  namespace: robotdreams
spec:
  type: NodePort
  selector:
    app: course-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
