apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-app-deployment
  labels:
    app: course-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: course-app
  template:
    metadata:
      labels:
        app: course-app
    spec:
      containers:
      - name: course-app
        image: sohatz/lesson-04-web:2.0
        ports:
        - containerPort: 8080
        env:
          - name: APP_STORE
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: APP_STORE
          - name: APP_REDIS_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: APP_REDIS_URL
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%  
---
apiVersion: v1
kind: Service
metadata:
  name: course-app-service
spec:
  type: NodePort
  selector:
    app: course-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000