FROM golang:1.23 AS build
WORKDIR /src
COPY ./apps/simple-app .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/simple-app ./main.go
EXPOSE 8080

FROM alpine
COPY --from=build /bin/simple-app /bin/simple-app
CMD ["cat", "/bin/simple-app"]
CMD ["ls", "-la", "/bin/simple-app"]
CMD ["sleep", "99999"]
